version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosmetics-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/cosmetics
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: focus0data
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cosmetics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: focus0data
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: