spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmetics
    username: postgres
    password: focus0data
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    changeLog: db/changelog/master.yaml